version: '3.5'
services:
  nginx-proxy:
    image: "${DOCKER_IMAGE_NGINX}"
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - session-data:/mnt/session-data
    networks:
      - InterventionEvaluatR
    restart: always

  interventionevaluatr:
    image: "${DOCKER_IMAGE_SHINYPROXY}"
    environment:
      - VIRTUAL_HOST=dev.interventionevaluatr.com
      - VIRTUAL_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - InterventionEvaluatR
    expose:
      - 8080
    restart: always

networks:
  InterventionEvaluatR:
    name: InterventionEvaluatR

volumes:
  session-data:
    name: session-data