#cloud-config
runcmd:
  # Start pulling the worker image ASAP because that's on the critical path to computation
  - while [ ! -d /etc/systemd/system/docker.service.d ] ; do sleep 1 ; done
  - sudo -u evaluatr docker login -u "${GITLAB_REGISTRY_USER}" -p "${GITLAB_REGISTRY_TOKEN}" "${GITLAB_REGISTRY}"
  - sudo -u evaluatr docker pull "${WORKER_IMAGE}"
users:
  - name: evaluatr
    groups: docker
    ssh-authorized-keys: 
      - "${WORKER_SSH_PUBKEY}"
write_files:
  - path: /usr/local/bin/Rscript-docker
    content: |
      #!/bin/bash
      docker login -u "${GITLAB_REGISTRY_USER}" -p "${GITLAB_REGISTRY_TOKEN}" "${GITLAB_REGISTRY}"
      exec /usr/bin/docker run --network host "${WORKER_IMAGE}" "$@"
    permissions: 0755
