proxy:
  port: 8080
  heartbeat-timeout: 21600000
  authentication: none
  hide-navbar: true
  template-path: /opt/shinyproxy/templates
  docker:
      internal-networking: true
  landing-page: /app/InterventionEvaluatR
  specs:
  - id: InterventionEvaluatR
    display-name: InterventionEvaluatR
    description: InterventionEvaluatR
    container-cmd: []
    container-image: ${APP_IMAGE}
    container-network: InterventionEvaluatR
    container-volumes:
      - session-data:/srv/shiny-server/WebUI/www/.session-data

logging:
  file:
    shinyproxy.log